// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCteF1DN0MZKh-1Z-BQK0gPwdkjcd-fXnc',
    appId: '1:679921037252:web:4aa9a456ec77efc4efbe91',
    messagingSenderId: '679921037252',
    projectId: 'mobowiza-app',
    authDomain: 'mobowiza-app.firebaseapp.com',
    storageBucket: 'mobowiza-app.firebasestorage.app',
    measurementId: 'G-ZZ1FWJTQB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC98DXwk8RgM14mIeQJiPL0Trx6CCh9Xfc',
    appId: '1:679921037252:android:f583b78ce43f199eefbe91',
    messagingSenderId: '679921037252',
    projectId: 'mobowiza-app',
    storageBucket: 'mobowiza-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfICy1jSysOAAyTG-8Cif4xR8_caVE_rg',
    appId: '1:679921037252:ios:302fbdbe96686b91efbe91',
    messagingSenderId: '679921037252',
    projectId: 'mobowiza-app',
    storageBucket: 'mobowiza-app.firebasestorage.app',
    androidClientId: '679921037252-rajvpgof7ko973b92gqaoqgcpb8j05p0.apps.googleusercontent.com',
    iosClientId: '679921037252-nmh9ep11t7puv7p3fl27mddaposcqgb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobodemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfICy1jSysOAAyTG-8Cif4xR8_caVE_rg',
    appId: '1:679921037252:ios:302fbdbe96686b91efbe91',
    messagingSenderId: '679921037252',
    projectId: 'mobowiza-app',
    storageBucket: 'mobowiza-app.firebasestorage.app',
    androidClientId: '679921037252-rajvpgof7ko973b92gqaoqgcpb8j05p0.apps.googleusercontent.com',
    iosClientId: '679921037252-nmh9ep11t7puv7p3fl27mddaposcqgb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobodemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCteF1DN0MZKh-1Z-BQK0gPwdkjcd-fXnc',
    appId: '1:679921037252:web:4eb57feb157ea316efbe91',
    messagingSenderId: '679921037252',
    projectId: 'mobowiza-app',
    authDomain: 'mobowiza-app.firebaseapp.com',
    storageBucket: 'mobowiza-app.firebasestorage.app',
    measurementId: 'G-00XDF002XY',
  );
}
