import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. Added this import
import 'firebase_options.dart'; // 2. Added this (Auto-generated by FlutterFire CLI)
import 'package:mobowiza/screens/splash_screen.dart';

void main() async {
  // 3. Essential for background platform communication
  WidgetsFlutterBinding.ensureInitialized();

  // 4. Start Firebase before the app UI builds
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const RepairLocateApp());
}

class RepairLocateApp extends StatelessWidget {
  const RepairLocateApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'RepairLocate',
      home: SplashScreen(), 
    );
  }
}